name: "Auto utpdate flake lock file"

on:
  workflow_call: ~
  workflow_dispatch:

jobs:
  auto-upgrade-flake-lock:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v8

      - name: Update flake.lock
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
          nix flake update --commit-lock-file --commit-lock-file-summary "$COMMIT_MSG"

      - name: Push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git push
